# NB! We are only using SAM to run the application as a Lambda function behind
# the API Gateway locally. We are actually using Terraform to describe and deploy
# the infrastructure (see `infra` directory in the project's root with IaC files, 
# specifically `infra/apigw.tf` and `infra/lambda.tf`).

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for running and tesing Onwards locally
Resources:
  OnwardsApi:
    Type: AWS::Serverless::Function
    # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/building-rust.html
    Metadata:
      BuildMethod: rust-cargolambda 
    Properties:
      CodeUri: .
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
      - x86_64
      Timeout: 29
      MemorySize: 512
      Events:
        Root:
          Type: HttpApi
          Properties:
            Path: /
            Method: get
        Forward:
          Type: HttpApi
          Properties:
            Path: /{short}
            Method: get
      Environment:
        Variables:
          RUST_LOG: debug
          USE_DYNAMODB: local
          AWS_ENDPOINT_URL: http://dynamodb-local:8000
